# Generated by Django 3.0.4 on 2020-04-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('contractor', models.CharField(max_length=200, verbose_name='合同方')),
                ('create_date', models.DateField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='子项目名称')),
                ('unit', models.CharField(max_length=200, verbose_name='单位')),
                ('contract_amount', models.FloatField(verbose_name='合同数量')),
                ('construction_amount', models.FloatField(verbose_name='施工图数量')),
                ('updated', models.BooleanField(default=False, verbose_name='变改设计')),
                ('updated_amount', models.FloatField(default=0, verbose_name='变改数量')),
                ('receivables', models.FloatField(verbose_name='应收款')),
                ('paid', models.FloatField(default=0, verbose_name='已收款')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects', to='my_app.Project', verbose_name='所属项目')),
            ],
        ),
    ]
