# Generated by Django 3.0.4 on 2020-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='finished_amount',
            field=models.FloatField(default=0, verbose_name='已完成数量'),
        ),
    ]
