# Generated by Django 3.0.4 on 2020-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_subproject_finished_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name': '子项目', 'verbose_name_plural': '子项目'},
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='paid',
        ),
        migrations.AddField(
            model_name='project',
            name='total_paid',
            field=models.FloatField(default=0, verbose_name='已收款'),
        ),
    ]
