# Generated by Django 3.0.4 on 2020-04-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200418_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
