# Generated by Django 3.0.4 on 2020-07-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('project_title', models.CharField(max_length=200)),
                ('project_nickname', models.CharField(max_length=200)),
                ('target_amount', models.FloatField(default=0)),
                ('current_amount', models.FloatField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('num_participants', models.IntegerField(default=0)),
                ('start_str', models.CharField(default='', max_length=200)),
                ('end_str', models.CharField(default='', max_length=200)),
                ('start_time', models.DateTimeField(null=True, verbose_name='time started')),
                ('end_time', models.DateTimeField(null=True, verbose_name='time ended')),
                ('is_expire', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_nickname', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='sunrui.Project')),
            ],
            options={
                'verbose_name': 'User Record',
                'verbose_name_plural': 'User Records',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_nickname', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('record_time', models.DateTimeField(null=True, verbose_name='record time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_list', to='sunrui.Project')),
            ],
            options={
                'verbose_name': 'Sale Record',
                'verbose_name_plural': 'Sale Records',
            },
        ),
    ]
