# Generated by Django 3.0.4 on 2020-07-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_nickname',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='amount',
        ),
        migrations.AddField(
            model_name='amount',
            name='chunk_fund',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='fund',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amount',
            name='time',
            field=models.DateTimeField(verbose_name='record time'),
        ),
    ]
