# Generated by Django 3.0.4 on 2020-07-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_str',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_str',
        ),
    ]
