# Generated by Django 3.0.4 on 2020-07-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0002_auto_20200706_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
