# Generated by Django 3.0.4 on 2020-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0002_auto_20200715_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_str',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='start_str',
            field=models.CharField(default='', max_length=200),
        ),
    ]
