# Generated by Django 3.0.4 on 2020-07-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0004_auto_20200706_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_nickname', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('time', models.DateTimeField(verbose_name='record time')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='fund',
            new_name='current_funding',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='amount_sold',
            new_name='sold_num',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_stock',
            new_name='stock_num',
        ),
        migrations.AddField(
            model_name='project',
            name='target_funding',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
        migrations.AddField(
            model_name='record',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunrui.Project'),
        ),
    ]
