# Generated by Django 3.0.4 on 2020-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrui', '0005_auto_20200707_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='record time'),
        ),
    ]
